name: Yoe Distro CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - dunfell
  pull_request:
    branches:
      - master
      - dunfell
jobs:
  build:
    name: Yoe Build
    runs-on: ubuntu-latest #[self-hosted, Linux]
    timeout-minutes: 720
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          #path: '${{ github.event.pull_request.head.sha }}'
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Setup
        run: |
          export LANG=en_US.UTF-8
          export SSTATE_CACHE_DIR=/scratch/sstate-cache
          echo export DOCKER_REPO=none > local.sh
          echo export LANG=en_US.UTF-8 >> local.sh
          echo export SSTATE_CACHE_DIR=/scratch/sstate-cache >> local.sh
          cp conf/local.conf.sample conf/local.conf
          echo SSTATE_DIR = \"$SSTATE_CACHE_DIR\" >> conf/local.conf
          echo IMAGE_CLASSES += \"testimage testsdk\" >> conf/local.conf
          echo INHERIT += \"report-error rm_work\" >> conf/local.conf
          echo ERR_REPORT_SERVER = \"errors.yoctoproject.org\" >> conf/local.conf
          echo ERR_REPORT_PORT = \"80\" >> conf/local.conf
          echo ERR_REPORT_USERNAME = \"Drone Autobuilder\" >> conf/local.conf
          echo ERR_REPORT_EMAIL = \"info@yoedistro.org\" >> conf/local.conf
          echo TOOLCHAIN = \"clang\" >> conf/local.conf
          /bin/bash -c "sed -i -e 's/PACKAGE_FEED_URI.*$//' conf/site.conf"
          /bin/bash -c "sed -i -e 's/SDK_UPDATE_URL.*$//' conf/site.conf"
      - name: Build Image
        run: |
          /bin/bash -c ". ./qemuarm64-envsetup.sh && bitbake yoe-qt5-image"
      - name: Test Image
        run: |
          echo TESTIMAGE_AUTO_qemuall = \"1\" >> conf/local.conf
          /bin/bash -c ". ./qemuarm64-envsetup.sh && bitbake yoe-sdk-image"
      - name: Prepare results
        run: |
          /bin/bash -c ". ./qemuarm64-envsetup.sh && resulttool report build/tmp/log/oeqa"
      - name: Clean shared state
        run: |
          /bin/bash -c ". ./qemuarm64-envsetup.sh && ./sources/openembedded-core/scripts/sstate-cache-management.sh -d -y"
